### ISSUE TITLE
Consolidate interpolation capability into SimplePlanner

### ISSUE THREAD

**Issue by marip8** [tesseract-robotics/tesseract_planning#158]
Several of the motion planners (namely `descartes` and `trajopt`) perform interpolation for MoveL/MoveJ instructions as a part of the planning process. This duplicates a lot of the functionality of the simple planner and makes the planners more complicated than they need to be. We should consolidate the interpolation features in the simple planner and simplify the other planner such that they only plan for the waypoints that are passed in

**Comment by Levi-Armstrong** [comment]
I believe this has been addressed with recent changes. Reopen if that is not the case.
