### ISSUE TITLE
Cartesian Path Constraint

### ISSUE THREAD

**Issue by cpetersmeier** [tesseract-robotics/tesseract_planning#196]
Hello everyone,

I am trying to configure a cartesian-path constraint by using the [constraint_error_functions](https://github.com/tesseract-robotics/tesseract_planning/blob/196b39b77e9542aa5e8991e7426ba3972412576a/tesseract_motion_planners/trajopt/include/tesseract_motion_planners/trajopt/profile/trajopt_default_plan_profile.h#L64-L83).

### Setup

The first element of the tuple that represents the vector's type is the error function, which has the following signature:
`std::function<Eigen::VectorXd(const Eigen::VectorXd &)> errorFunction;`

I would like to provide an implementation for this function which uses the current position of the tcp. Thus I would have to calculate the forward kinematics inside this function.

Using the environment object, I found that the calculation of the forward kinematics could be done in the following manner:
```
jointGroup = env->getJointGroup("manipulator");
tesseract_common::TransformMap tm = jointGroup->calcFwdKin(jointValues);
```

### Question

My question is how to access any environment or joint group object since the signature of the error function is fixed and it should be in global scope (?).

Thanks very much in advance!

**Comment by Levi-Armstrong** [comment]
That was carried over from the original implementation and you would need to capture the environment when creating the function. This most likely is not ideal and should be changed to be a factory that produces this object which is give the environment when the profile is called during problem setup. I recommend creating your own profile which either inherits form the default one or role your own by implementing the required methods.
