### ISSUE TITLE
Excess Collision Checking in Continuous Collision Checking

### ISSUE THREAD

**Issue by marrts** [tesseract-robotics/tesseract_planning#201]
https://github.com/tesseract-robotics/tesseract_planning/blob/9d08e6a0a995e422a858c9fb254306dc47253514/tesseract_motion_planners/core/src/core/utils.cpp#L317-L374
This appears to iterate over every step every time any adjacent step has a distance less than the LVS, potentially causing an n^2 order of magnitude increase in computation. It should just be doing collision checking between the already made swp0 and swp1.

**Comment by Levi-Armstrong** [comment]
WOW, good find.
