### ISSUE TITLE
Pilz integration

### ISSUE THREAD

**Issue by johnwason** [tesseract-robotics/tesseract_planning#210]
Move-It has added a pilz module. Having this available in Tesseract would be helpful for industrial robot integration.

https://ros-planning.github.io/moveit_tutorials/doc/pilz_industrial_motion_planner/pilz_industrial_motion_planner.html

https://github.com/PilzDE/pilz_industrial_motion

**Comment by Levi-Armstrong** [comment]
It should not be to difficult to added. Unfortunately it is integrated with ros so it go in this repository but could be a separate repository.

**Comment by johnwason** [comment]
The source for the planner itself is here: https://github.com/ros-planning/moveit/tree/master/moveit_planners/pilz_industrial_motion_planner

It doesn't look like it would be too difficult to swap out the ROS types for Tesseract types. It will just be a little tedious.

**Comment by johnwason** [comment]
After looking in more detail, pilz is using a very naïve approach to segment blending. I wouldn't recommend using it.
