### ISSUE TITLE
Build failure on utility function templates

### ISSUE THREAD

**Issue by cpetersmeier** [tesseract-robotics/tesseract_planning#220]
Commit https://github.com/tesseract-robotics/tesseract/commit/f91c9b6aa907de39cc853a95583a29dc5f35420c introduced templating on utility functions. I think the function calls in the `tesseract_motion_planners` package should be ported to support that.

I created a test branch here https://github.com/tesseract-robotics/tesseract_planning/pull/221

**Comment by Levi-Armstrong** [comment]
Addressed by PR #221, just a heads up we will be making some big changes in tesseract_planning to improve ease of use.
