### ISSUE TITLE
unable to build tesseract_command_language due to isNull not available as member function of some structs

### ISSUE THREAD

**Issue by thomasw2** [tesseract-robotics/tesseract_planning#244]
We tried to build some tesseract repositories in a catkin workspace. When building, we encountered an error:
![tesseract_error](https://user-images.githubusercontent.com/27076313/189006467-5a19e35e-2428-4ef7-b4cf-f10e03fffb1e.png)

we had the following repos in src during building:
descartes_light, ifopt, osqp, ros_industrial_cmake_boilerplate, tesseract, tesseract_planning, tesseract_ros, trajopt
The tesseract repos were all on master branch. 
Our system is Ubuntu 20.04, running ROS Noetic. We cloned the above repos and ran catkin build.
Are there any suggestions for how to get around this issue?

**Comment by Levi-Armstrong** [comment]
Can you provide the tags/branches for each of the repositories? The tesseract repositories I recommend using the latest tag 0.13.X where the X may be different on each repository.

**Comment by Levi-Armstrong** [comment]
Can you check the latest tag on tesseract, tesseract_planning, tesseract_qt and tesseract_ros. It should be 0.13.X?

**Comment by Levi-Armstrong** [comment]
Reopen if still an issue
