### ISSUE TITLE
whrn run  ./tesseract_motion_planners_chain_example ,it shows error to load plugin TesseractIgnitionVisualizationPlugin for plot trajectory

### ISSUE THREAD

**Issue by dbdxnuliba** [tesseract-robotics/tesseract_planning#246]
robot@robot-NUC8i7BEH:~/ws_tesseract_new/devel/bin$ ./tesseract_motion_planners_chain_example
You can set logging level with TRAJOPT_LOG_THRESH. Valid values: FATAL ERROR WARN INFO DEBUG TRACE. Defaulting to ERROR
Error: Failed to instantiate plugin 'TesseractIgnitionVisualizationPlugin', Details:
Search Paths (Search System Folders: True):
- /home/robot/ws_tesseract_new/devel/lib
Search Libraries:
- libtesseract_visualization_ignition_visualization_plugin.so

     at line 161 in /home/robot/ws_tesseract_new/devel/include/tesseract_common/plugin_loader.hpp
When I try catkin build tesseract_ignition ，I found it's version is so old that can't be compatible for new tesseraction_motion_planner

**Comment by dbdxnuliba** [comment]
I add    use ROSPlotting to replace libtesseract_visualization_ignition_visualization_plugin to finish plot it ,the gif  was shown as followed:
```
ROSPlottingPtr plotter;
  if (plotting)
    plotter = std::make_shared<ROSPlotting>(env->getSceneGraph()->getRoot());
```

![chain_example](https://user-images.githubusercontent.com/13350158/190112391-ea3795dd-b9c0-449e-8cd1-eee95e20683e.gif)

you can close the issue, thanks a lot

**Comment by dbdxnuliba** [comment]
![chain_example](https://user-images.githubusercontent.com/13350158/190112931-9e8dda98-9898-4514-bef9-6b8add6ea1ca.gif)

**Comment by Levi-Armstrong** [comment]
Yea, this package is ros agnostic so we have another visualizer to work for those not using ros. All of the examples in tesseract_examples can be ran from the tesseract_ros_example which provides launch files with rviz already setup for visualization.
