### ISSUE TITLE
when catkin build tesseract_planning-0.13.1 on ubuntu20.04 ,it show required from here /usr/include/c++/9/ext/new_allocator.h:146:4: error: invalid new-expression of abstract class type 'descartes_light::StateEvaluator<float>'   146 |  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }

### ISSUE THREAD

**Issue by dbdxnuliba** [tesseract-robotics/tesseract_planning#250]
![image](https://user-images.githubusercontent.com/13350158/191157442-e9cee759-3062-448e-b99b-a21d8de7eb0d.png)

/home/taimi/ws_tesseract_060/src/tesseract_planning-0.13.1/tesseract_motion_planners/descartes/src/profile/descartes_default_plan_profile.cpp:31:16:   required from here
/usr/include/c++/9/ext/new_allocator.h:146:4: error: invalid new-expression of abstract class type 'descartes_light::StateEvaluator<float>'
  146 |  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Levi-Armstrong** [comment]
Reopen if still an issue.
