### ISSUE TITLE
error when building tesseract task composer

### ISSUE THREAD

**Issue by zhiyong-009** [tesseract-robotics/tesseract_planning#286]
fatal error: tesseract_environment/environment.h: No such file or directory
   37 | #include <tesseract_environment/environment.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/tesseract_task_composer_taskflow.dir/build.make:63: CMakeFiles/tesseract_task_composer_taskflow.dir/src/taskflow/taskflow_task_composer_executor.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:329: CMakeFiles/tesseract_task_composer_taskflow.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:130: all] Error 2
---
Failed   <<< tesseract_task_composer [2min 20s, exited with code 2]

I have sourced the workspace, have tesseract installed in the workspace  but i keep getting this error what should i be doing?

**Comment by Levi-Armstrong** [comment]
https://tesseract-docs.readthedocs.io/en/latest/_source/intro/getting_started_doc.html

**Comment by zhiyong-009** [comment]
Thanks for the suggestions!  I understand which this is a basic question, i am perplexed as I have installed the newest version of the tesseract package and tesseract planning, i have sourced the workspace but when i build using colcon build there is this error,
correct me if im wrong, the tesseract task composer component requires this header file tesseract_environment/environment.h, which is under the tesseract package but when i build my virtual machine cannot seem to find the header file, what could be the error?

**Comment by Levi-Armstrong** [comment]
Make sure you do not have tesseract installed in /opt/ros/<distro>. If you find any packages installed here uninstall them.

**Comment by zhiyong-009** [comment]
thank you
