### ISSUE TITLE
Task Composer Configuration File Loading

### ISSUE THREAD

**Issue by marip8** [tesseract-robotics/tesseract_planning#301]
Is the following function intended to load the task composer config from a string filename or a YAML string? This does not appear to be tested in any unit tests yet.

https://github.com/tesseract-robotics/tesseract_planning/blob/e92083398c11da5a808794bed82cec392f2c4625/tesseract_task_composer/src/task_composer_plugin_factory.cpp#L89

If the intent is to load from a string filename (as in most applications I have encountered so far), then this function needs to use `YAML::LoadFile` instead of `YAML::Load`

**Comment by Levi-Armstrong** [comment]
The header documentation state that it is loading it as a string. The method above states loading from file using `tesseract_common::fs::path`.

**Comment by Levi-Armstrong** [comment]
Probably good to update the header to state yaml string to avoid confusion.

**Comment by Levi-Armstrong** [comment]
I believe this can be closed. Reopen if not the case.
