### ISSUE TITLE
could you please give us a demo which use the project in real enviroment and robot ,sow we can use your project convinently 

### ISSUE THREAD

**Issue by dbdxnuliba** [tesseract-robotics/tesseract_planning#307]
could you please give us a demo which use the project in real enviroment and robot ,sow we can use your project convinently 

such as universal robot or iiwa robot with 3D camera ,I think once you add the interface to real robot and environment point_cloud from 3D camear, the project will be tested and used by much more peoples

**Comment by Levi-Armstrong** [comment]
I think this is what you are looking for. It does not appear to be upgraded the latest version of Tesseract.
https://github.com/ros-industrial-consortium/scan_n_plan_workshop

**Comment by marrts** [comment]
This is up to date now
