### ISSUE TITLE
Serialization of trajopt_ifopt profiles is missing

### ISSUE THREAD

**Issue by rjoomen** [tesseract-robotics/tesseract_planning#311]
The trajopt_ifopt profiles lack serialization (e.g. tesseract_planning::trajOptIfOptCompositeFromXMLFile()).

**Comment by Levi-Armstrong** [comment]
Thanks for reporting. @marip8 is working on a restructure of the profiles to support boost serialization and loading profiles as plugins like how tasks and executors are now loaded. This will make task_composer easier to customize using a yaml file.

**Comment by rjoomen** [comment]
Thanks for the quick reply, that sounds as a nice improvement.

**Comment by Levi-Armstrong** [comment]
This is planned to be replace as part of the profile refactor.
