### ISSUE TITLE
Segfault in cartesian_waypoint_poly_unit.hpp test

### ISSUE THREAD

**Issue by johnwason** [tesseract-robotics/tesseract_planning#335]
I am getting segfaults on this line of the command language tests:

https://github.com/tesseract-robotics/tesseract_planning/blob/e3013c650d3a357e65edb727eee4ec48ac5ec9ea/tesseract_command_language/include/tesseract_command_language/test_suite/cartesian_waypoint_poly_unit.hpp#L199

**Comment by Levi-Armstrong** [comment]
I will get it fixed.

**Comment by Levi-Armstrong** [comment]
Oh, the focal build fails but the Unstable succeeds. This is accurate because the fix had to happen in tesseract so the focal build will fail.
