### ISSUE TITLE
Could not find package configuration provided by benchmark

### ISSUE THREAD

**Issue by prajwalthakur** [tesseract-robotics/tesseract_planning#368]
Hi,
I have followed the steps listed : [tesseract-get-started](https://tesseract-docs.readthedocs.io/en/latest/_source/intro/getting_started_doc.html)
![error](https://github.com/tesseract-robotics/tesseract_planning/assets/42039745/f3b02416-5e97-46bc-a61c-5fe11fa2931f)

except : rosdep install -y --from-paths ~/tesseract_ws/src --ignore-src --rosdistro noetic .
when I try to build using this command :catkin build --force-cmake -DTESSERACT_ENABLE_TESTING=ON -DTRAJOPT_ENABLE_TESTING=ON . I get the error as shown in the figure . Can anyone help to figure out how to resolve this?
ps: I am trying to run trajopt examples in ros.

**Comment by Levi-Armstrong** [comment]
Remove these command `-DTESSERACT_ENABLE_TESTING=ON -DTRAJOPT_ENABLE_TESTING=ON` because I assume you are not wanting to run unit tests or benchmarks. If that is your attempt then install google banchmark and gtest `sudo apt install libgtest-dev libbenchmark-dev`.

**Comment by prajwalthakur** [comment]
Thanks .
