### ISSUE TITLE
Using Convex Decomposition for Collision Geometry

### ISSUE THREAD

**Issue by emfebert** [tesseract-robotics/tesseract_planning#372]
I'm trying to import a custom workcell environment, is there a way to use VHACD for convex composition? I saw it's used somewhere in the code.

Here's the orginial workcell geometry:
![Screenshot from 2023-09-04 15-28-59](https://github.com/tesseract-robotics/tesseract_planning/assets/128838660/65a43aab-817e-4b32-be4f-bec603dd21dd)

And this is the result:
![Screenshot from 2023-09-04 15-28-37](https://github.com/tesseract-robotics/tesseract_planning/assets/128838660/1bb5b4ac-806c-4257-a77e-3bc0b0bbfe98)

_Originally posted by @emfebert in https://github.com/tesseract-robotics/tesseract_planning/issues/369#issuecomment-1705746903_

**Comment by rjoomen** [comment]
Here is some example code:

```
auto ConvexDecomposition(const tesseract_geometry::Mesh& mesh, int max_convex_hulls)
    -> std::vector<tesseract_geometry::ConvexMesh::Ptr>
{
  tesseract_collision::VHACDParameters params;
  params.find_best_plane = true;
  params.max_convex_hulls = max_convex_hulls;
  params.resolution = 1e6;
  tesseract_collision::ConvexDecompositionVHACD convex_decomp(params);
  std::vector<tesseract_geometry::ConvexMesh::Ptr> convex_meshes =
      convex_decomp.compute(*mesh.getVertices(), *mesh.getFaces());
  return convex_meshes;
}
```

**Comment by Levi-Armstrong** [comment]
It should generate a command line tool that you can run to avoid having to write any code. I will take a look and make sure this is true.

**Comment by Levi-Armstrong** [comment]
The executable is called `create_convex_hull` which you can run the with `-h` to get information on how to run it.

**Comment by Levi-Armstrong** [comment]
Actually I think that only creates a convex hull and I don't see one for the convex decomposition.

**Comment by emfebert** [comment]
Thanks for the pointers! I ended up using the original V-HACD repo https://github.com/kmammou/v-hacd since it was simple and quick to do.
