### ISSUE TITLE
Patch 0.20.1 build

### ISSUE THREAD

**Issue by marip8** [tesseract-robotics/tesseract_planning#400]
Building 0.20.1 of this repo with 0.20.1 of `tesseract` results in a build failure because the header clean up from https://github.com/tesseract-robotics/tesseract/pull/946 removed some headers that were implicitly included in `tesseract_planning`. This issue was fixed in #394, but only after breaking changes were introduced in this repo to support a later version of `trajopt`.

What is the right way of patching the 0.20.1 build to include this fix? Separate branch, re-arrange commits on master branch?

**Comment by Levi-Armstrong** [comment]
I would create a branch from the 0.20.1 tag and apply the patch then create a 0.20.2 tag from this branch then the branch can be deleted.

**Comment by Levi-Armstrong** [comment]
I don't think you will be able to use the catkin_prepare_release but you should be able to use the catkin_generate_changelog to update the change log and then manually push to the patch branch and then create tag.

**Comment by marip8** [comment]
> I would create a branch from the 0.20.1 tag and apply the patch then create a 0.20.2 tag from this branch then the branch can be deleted.

I thought of this last night as well; I'll give it a shot

**Comment by marip8** [comment]
Closing; I think this should work fine
