### ISSUE TITLE
Save DOT file inside registerProcessPlanner

### ISSUE THREAD

**Issue by mpowelson** [tesseract-robotics/tesseract_planning#62]
Not an essential feature, but  I would find it convenient to save the DOT file for the taskflow on startup. I'm not sure if this is possible without adding a new method to the TaskGenerator. We may be able to make a TaskInput that just has nullptrs in it. When I am tweaking things I frequently end up just commenting that log level check out and saving it on each request.

**Comment by Levi-Armstrong** [comment]
This possible not from request.
