### ISSUE TITLE
TrajOpt Motion Planner Enforce Kinematic Limits Assertion Bug

### ISSUE THREAD

**Issue by marip8** [tesseract-robotics/tesseract_planning#94]
The current TrajOpt motion planner asserts that the trajectory produced by TrajOpt lies within the kinematic limits but subsequently enforces kinematic limits anyway.

https://github.com/ros-industrial-consortium/tesseract_planning/blob/5b09248852f861c57dbdb20e5c9cabe6647e957a/tesseract_motion_planners/src/trajopt/trajopt_motion_planner.cpp#L167-L172

This seems contradictory and causes faults for anyone running a debug build. Is there a reason for this assert? If not it seems like it should be removed. I commented it out for a planning problem where the assertion was previously failing, and the resulting trajectory still seems to be valid after the kinematic limits are enforced.

**Comment by Levi-Armstrong** [comment]
Ideally trajopt should not be producing a trajectory that violates kinematic limits. A while back I updated the tolerance of this to be compatible with trajopts tolerance. If it is continuing to fail then there may be another issues that needs to be investigated.
